#|
 This file is a part of Lionchat
 (c) 2018 Shirakumo http://tymoon.eu (shinmera@tymoon.eu)
 Author: Nicolas Hafner <shinmera@tymoon.eu>
|#

(in-package #:org.shirakumo.lionchat)

(defvar *icon-name-map*
  (let ((table (make-hash-table :test 'eq)))
    (loop for (k v) on '(:500px #xf26e
                         :accessible-icon #xf368
                         :accusoft #xf369
                         :address-book #xf2b9
                         :address-card #xf2bb
                         :adjust #xf042
                         :adn #xf170
                         :adversal #xf36a
                         :affiliatetheme #xf36b
                         :algolia #xf36c
                         :align-center #xf037
                         :align-justify #xf039
                         :align-left #xf036
                         :align-right #xf038
                         :allergies #xf461
                         :amazon #xf270
                         :amazon-pay #xf42c
                         :ambulance #xf0f9
                         :american-sign-language-interpreting #xf2a3
                         :amilia #xf36d
                         :anchor #xf13d
                         :android #xf17b
                         :angellist #xf209
                         :angle-double-down #xf103
                         :angle-double-left #xf100
                         :angle-double-right #xf101
                         :angle-double-up #xf102
                         :angle-down #xf107
                         :angle-left #xf104
                         :angle-right #xf105
                         :angle-up #xf106
                         :angrycreative #xf36e
                         :angular #xf420
                         :app-store #xf36f
                         :app-store-ios #xf370
                         :apper #xf371
                         :apple #xf179
                         :apple-pay #xf415
                         :archive #xf187
                         :arrow-alt-circle-down #xf358
                         :arrow-alt-circle-left #xf359
                         :arrow-alt-circle-right #xf35a
                         :arrow-alt-circle-up #xf35b
                         :arrow-circle-down #xf0ab
                         :arrow-circle-left #xf0a8
                         :arrow-circle-right #xf0a9
                         :arrow-circle-up #xf0aa
                         :arrow-down #xf063
                         :arrow-left #xf060
                         :arrow-right #xf061
                         :arrow-up #xf062
                         :arrows-alt #xf0b2
                         :arrows-alt-h #xf337
                         :arrows-alt-v #xf338
                         :assistive-listening-systems #xf2a2
                         :asterisk #xf069
                         :asymmetrik #xf372
                         :at #xf1fa
                         :audible #xf373
                         :audio-description #xf29e
                         :autoprefixer #xf41c
                         :avianex #xf374
                         :aviato #xf421
                         :aws #xf375
                         :backward #xf04a
                         :balance-scale #xf24e
                         :ban #xf05e
                         :band-aid #xf462
                         :bandcamp #xf2d5
                         :barcode #xf02a
                         :bars #xf0c9
                         :baseball-ball #xf433
                         :basketball-ball #xf434
                         :bath #xf2cd
                         :battery-empty #xf244
                         :battery-full #xf240
                         :battery-half #xf242
                         :battery-quarter #xf243
                         :battery-three-quarters #xf241
                         :bed #xf236
                         :beer #xf0fc
                         :behance #xf1b4
                         :behance-square #xf1b5
                         :bell #xf0f3
                         :bell-slash #xf1f6
                         :bicycle #xf206
                         :bimobject #xf378
                         :binoculars #xf1e5
                         :birthday-cake #xf1fd
                         :bitbucket #xf171
                         :bitcoin #xf379
                         :bity #xf37a
                         :black-tie #xf27e
                         :blackberry #xf37b
                         :blind #xf29d
                         :blogger #xf37c
                         :blogger-b #xf37d
                         :bluetooth #xf293
                         :bluetooth-b #xf294
                         :bold #xf032
                         :bolt #xf0e7
                         :bomb #xf1e2
                         :book #xf02d
                         :bookmark #xf02e
                         :bowling-ball #xf436
                         :box #xf466
                         :box-open #xf49e
                         :boxes #xf468
                         :braille #xf2a1
                         :briefcase #xf0b1
                         :briefcase-medical #xf469
                         :btc #xf15a
                         :bug #xf188
                         :building #xf1ad
                         :bullhorn #xf0a1
                         :bullseye #xf140
                         :burn #xf46a
                         :buromobelexperte #xf37f
                         :bus #xf207
                         :buysellads #xf20d
                         :calculator #xf1ec
                         :calendar #xf133
                         :calendar-alt #xf073
                         :calendar-check #xf274
                         :calendar-minus #xf272
                         :calendar-plus #xf271
                         :calendar-times #xf273
                         :camera #xf030
                         :camera-retro #xf083
                         :capsules #xf46b
                         :car #xf1b9
                         :caret-down #xf0d7
                         :caret-left #xf0d9
                         :caret-right #xf0da
                         :caret-square-down #xf150
                         :caret-square-left #xf191
                         :caret-square-right #xf152
                         :caret-square-up #xf151
                         :caret-up #xf0d8
                         :cart-arrow-down #xf218
                         :cart-plus #xf217
                         :cc-amazon-pay #xf42d
                         :cc-amex #xf1f3
                         :cc-apple-pay #xf416
                         :cc-diners-club #xf24c
                         :cc-discover #xf1f2
                         :cc-jcb #xf24b
                         :cc-mastercard #xf1f1
                         :cc-paypal #xf1f4
                         :cc-stripe #xf1f5
                         :cc-visa #xf1f0
                         :centercode #xf380
                         :certificate #xf0a3
                         :chart-area #xf1fe
                         :chart-bar #xf080
                         :chart-line #xf201
                         :chart-pie #xf200
                         :check #xf00c
                         :check-circle #xf058
                         :check-square #xf14a
                         :chess #xf439
                         :chess-bishop #xf43a
                         :chess-board #xf43c
                         :chess-king #xf43f
                         :chess-knight #xf441
                         :chess-pawn #xf443
                         :chess-queen #xf445
                         :chess-rook #xf447
                         :chevron-circle-down #xf13a
                         :chevron-circle-left #xf137
                         :chevron-circle-right #xf138
                         :chevron-circle-up #xf139
                         :chevron-down #xf078
                         :chevron-left #xf053
                         :chevron-right #xf054
                         :chevron-up #xf077
                         :child #xf1ae
                         :chrome #xf268
                         :circle #xf111
                         :circle-notch #xf1ce
                         :clipboard #xf328
                         :clipboard-check #xf46c
                         :clipboard-list #xf46d
                         :clock #xf017
                         :clone #xf24d
                         :closed-captioning #xf20a
                         :cloud #xf0c2
                         :cloud-download-alt #xf381
                         :cloud-upload-alt #xf382
                         :cloudscale #xf383
                         :cloudsmith #xf384
                         :cloudversify #xf385
                         :code #xf121
                         :code-branch #xf126
                         :codepen #xf1cb
                         :codiepie #xf284
                         :coffee #xf0f4
                         :cog #xf013
                         :cogs #xf085
                         :columns #xf0db
                         :comment #xf075
                         :comment-alt #xf27a
                         :comment-dots #xf4ad
                         :comment-slash #xf4b3
                         :comments #xf086
                         :compass #xf14e
                         :compress #xf066
                         :connectdevelop #xf20e
                         :contao #xf26d
                         :copy #xf0c5
                         :copyright #xf1f9
                         :couch #xf4b8
                         :cpanel #xf388
                         :creative-commons #xf25e
                         :credit-card #xf09d
                         :crop #xf125
                         :crosshairs #xf05b
                         :css3 #xf13c
                         :css3-alt #xf38b
                         :cube #xf1b2
                         :cubes #xf1b3
                         :cut #xf0c4
                         :cuttlefish #xf38c
                         :d-and-d #xf38d
                         :dashcube #xf210
                         :database #xf1c0
                         :deaf #xf2a4
                         :delicious #xf1a5
                         :deploydog #xf38e
                         :deskpro #xf38f
                         :desktop #xf108
                         :deviantart #xf1bd
                         :diagnoses #xf470
                         :digg #xf1a6
                         :digital-ocean #xf391
                         :discord #xf392
                         :discourse #xf393
                         :dna #xf471
                         :dochub #xf394
                         :docker #xf395
                         :dollar-sign #xf155
                         :dolly #xf472
                         :dolly-flatbed #xf474
                         :donate #xf4b9
                         :dot-circle #xf192
                         :dove #xf4ba
                         :download #xf019
                         :draft2digital #xf396
                         :dribbble #xf17d
                         :dribbble-square #xf397
                         :dropbox #xf16b
                         :drupal #xf1a9
                         :dyalog #xf399
                         :earlybirds #xf39a
                         :edge #xf282
                         :edit #xf044
                         :eject #xf052
                         :elementor #xf430
                         :ellipsis-h #xf141
                         :ellipsis-v #xf142
                         :ember #xf423
                         :empire #xf1d1
                         :envelope #xf0e0
                         :envelope-open #xf2b6
                         :envelope-square #xf199
                         :envira #xf299
                         :eraser #xf12d
                         :erlang #xf39d
                         :ethereum #xf42e
                         :etsy #xf2d7
                         :euro-sign #xf153
                         :exchange-alt #xf362
                         :exclamation #xf12a
                         :exclamation-circle #xf06a
                         :exclamation-triangle #xf071
                         :expand #xf065
                         :expand-arrows-alt #xf31e
                         :expeditedssl #xf23e
                         :external-link-alt #xf35d
                         :external-link-square-alt #xf360
                         :eye #xf06e
                         :eye-dropper #xf1fb
                         :eye-slash #xf070
                         :facebook #xf09a
                         :facebook-f #xf39e
                         :facebook-messenger #xf39f
                         :facebook-square #xf082
                         :fast-backward #xf049
                         :fast-forward #xf050
                         :fax #xf1ac
                         :female #xf182
                         :fighter-jet #xf0fb
                         :file #xf15b
                         :file-alt #xf15c
                         :file-archive #xf1c6
                         :file-audio #xf1c7
                         :file-code #xf1c9
                         :file-excel #xf1c3
                         :file-image #xf1c5
                         :file-medical #xf477
                         :file-medical-alt #xf478
                         :file-pdf #xf1c1
                         :file-powerpoint #xf1c4
                         :file-video #xf1c8
                         :file-word #xf1c2
                         :film #xf008
                         :filter #xf0b0
                         :fire #xf06d
                         :fire-extinguisher #xf134
                         :firefox #xf269
                         :first-aid #xf479
                         :first-order #xf2b0
                         :firstdraft #xf3a1
                         :flag #xf024
                         :flag-checkered #xf11e
                         :flask #xf0c3
                         :flickr #xf16e
                         :flipboard #xf44d
                         :fly #xf417
                         :folder #xf07b
                         :folder-open #xf07c
                         :font #xf031
                         :font-awesome #xf2b4
                         :font-awesome-alt #xf35c
                         :font-awesome-flag #xf425
                         :fonticons #xf280
                         :fonticons-fi #xf3a2
                         :football-ball #xf44e
                         :fort-awesome #xf286
                         :fort-awesome-alt #xf3a3
                         :forumbee #xf211
                         :forward #xf04e
                         :foursquare #xf180
                         :free-code-camp #xf2c5
                         :freebsd #xf3a4
                         :frown #xf119
                         :futbol #xf1e3
                         :gamepad #xf11b
                         :gavel #xf0e3
                         :gem #xf3a5
                         :genderless #xf22d
                         :get-pocket #xf265
                         :gg #xf260
                         :gg-circle #xf261
                         :gift #xf06b
                         :git #xf1d3
                         :git-square #xf1d2
                         :github #xf09b
                         :github-alt #xf113
                         :github-square #xf092
                         :gitkraken #xf3a6
                         :gitlab #xf296
                         :gitter #xf426
                         :glass-martini #xf000
                         :glide #xf2a5
                         :glide-g #xf2a6
                         :globe #xf0ac
                         :gofore #xf3a7
                         :golf-ball #xf450
                         :goodreads #xf3a8
                         :goodreads-g #xf3a9
                         :google #xf1a0
                         :google-drive #xf3aa
                         :google-play #xf3ab
                         :google-plus #xf2b3
                         :google-plus-g #xf0d5
                         :google-plus-square #xf0d4
                         :google-wallet #xf1ee
                         :graduation-cap #xf19d
                         :gratipay #xf184
                         :grav #xf2d6
                         :gripfire #xf3ac
                         :grunt #xf3ad
                         :gulp #xf3ae
                         :h-square #xf0fd
                         :hacker-news #xf1d4
                         :hacker-news-square #xf3af
                         :hand-holding #xf4bd
                         :hand-holding-heart #xf4be
                         :hand-holding-usd #xf4c0
                         :hand-lizard #xf258
                         :hand-paper #xf256
                         :hand-peace #xf25b
                         :hand-point-down #xf0a7
                         :hand-point-left #xf0a5
                         :hand-point-right #xf0a4
                         :hand-point-up #xf0a6
                         :hand-pointer #xf25a
                         :hand-rock #xf255
                         :hand-scissors #xf257
                         :hand-spock #xf259
                         :hands #xf4c2
                         :hands-helping #xf4c4
                         :handshake #xf2b5
                         :hashtag #xf292
                         :hdd #xf0a0
                         :heading #xf1dc
                         :headphones #xf025
                         :heart #xf004
                         :heartbeat #xf21e
                         :hips #xf452
                         :hire-a-helper #xf3b0
                         :history #xf1da
                         :hockey-puck #xf453
                         :home #xf015
                         :hooli #xf427
                         :hospital #xf0f8
                         :hospital-alt #xf47d
                         :hospital-symbol #xf47e
                         :hotjar #xf3b1
                         :hourglass #xf254
                         :hourglass-end #xf253
                         :hourglass-half #xf252
                         :hourglass-start #xf251
                         :houzz #xf27c
                         :html5 #xf13b
                         :hubspot #xf3b2
                         :i-cursor #xf246
                         :id-badge #xf2c1
                         :id-card #xf2c2
                         :id-card-alt #xf47f
                         :image #xf03e
                         :images #xf302
                         :imdb #xf2d8
                         :inbox #xf01c
                         :indent #xf03c
                         :industry #xf275
                         :info #xf129
                         :info-circle #xf05a
                         :instagram #xf16d
                         :internet-explorer #xf26b
                         :ioxhost #xf208
                         :italic #xf033
                         :itunes #xf3b4
                         :itunes-note #xf3b5
                         :jenkins #xf3b6
                         :joget #xf3b7
                         :joomla #xf1aa
                         :js #xf3b8
                         :js-square #xf3b9
                         :jsfiddle #xf1cc
                         :key #xf084
                         :keyboard #xf11c
                         :keycdn #xf3ba
                         :kickstarter #xf3bb
                         :kickstarter-k #xf3bc
                         :korvue #xf42f
                         :language #xf1ab
                         :laptop #xf109
                         :laravel #xf3bd
                         :lastfm #xf202
                         :lastfm-square #xf203
                         :leaf #xf06c
                         :leanpub #xf212
                         :lemon #xf094
                         :less #xf41d
                         :level-down-alt #xf3be
                         :level-up-alt #xf3bf
                         :life-ring #xf1cd
                         :lightbulb #xf0eb
                         :line #xf3c0
                         :link #xf0c1
                         :linkedin #xf08c
                         :linkedin-in #xf0e1
                         :linode #xf2b8
                         :linux #xf17c
                         :lira-sign #xf195
                         :list #xf03a
                         :list-alt #xf022
                         :list-ol #xf0cb
                         :list-ul #xf0ca
                         :location-arrow #xf124
                         :lock #xf023
                         :lock-open #xf3c1
                         :long-arrow-alt-down #xf309
                         :long-arrow-alt-left #xf30a
                         :long-arrow-alt-right #xf30b
                         :long-arrow-alt-up #xf30c
                         :low-vision #xf2a8
                         :lyft #xf3c3
                         :magento #xf3c4
                         :magic #xf0d0
                         :magnet #xf076
                         :male #xf183
                         :map #xf279
                         :map-marker #xf041
                         :map-marker-alt #xf3c5
                         :map-pin #xf276
                         :map-signs #xf277
                         :mars #xf222
                         :mars-double #xf227
                         :mars-stroke #xf229
                         :mars-stroke-h #xf22b
                         :mars-stroke-v #xf22a
                         :maxcdn #xf136
                         :medapps #xf3c6
                         :medium #xf23a
                         :medium-m #xf3c7
                         :medkit #xf0fa
                         :medrt #xf3c8
                         :meetup #xf2e0
                         :meh #xf11a
                         :mercury #xf223
                         :microchip #xf2db
                         :microphone #xf130
                         :microphone-slash #xf131
                         :microsoft #xf3ca
                         :minus #xf068
                         :minus-circle #xf056
                         :minus-square #xf146
                         :mix #xf3cb
                         :mixcloud #xf289
                         :mizuni #xf3cc
                         :mobile #xf10b
                         :mobile-alt #xf3cd
                         :modx #xf285
                         :monero #xf3d0
                         :money-bill-alt #xf3d1
                         :moon #xf186
                         :motorcycle #xf21c
                         :mouse-pointer #xf245
                         :music #xf001
                         :napster #xf3d2
                         :neuter #xf22c
                         :newspaper #xf1ea
                         :nintendo-switch #xf418
                         :node #xf419
                         :node-js #xf3d3
                         :notes-medical #xf481
                         :npm #xf3d4
                         :ns8 #xf3d5
                         :nutritionix #xf3d6
                         :object-group #xf247
                         :object-ungroup #xf248
                         :odnoklassniki #xf263
                         :odnoklassniki-square #xf264
                         :opencart #xf23d
                         :openid #xf19b
                         :opera #xf26a
                         :optin-monster #xf23c
                         :osi #xf41a
                         :outdent #xf03b
                         :page4 #xf3d7
                         :pagelines #xf18c
                         :paint-brush #xf1fc
                         :palfed #xf3d8
                         :pallet #xf482
                         :paper-plane #xf1d8
                         :paperclip #xf0c6
                         :parachute-box #xf4cd
                         :paragraph #xf1dd
                         :paste #xf0ea
                         :patreon #xf3d9
                         :pause #xf04c
                         :pause-circle #xf28b
                         :paw #xf1b0
                         :paypal #xf1ed
                         :pen-square #xf14b
                         :pencil-alt #xf303
                         :people-carry #xf4ce
                         :percent #xf295
                         :periscope #xf3da
                         :phabricator #xf3db
                         :phoenix-framework #xf3dc
                         :phone #xf095
                         :phone-slash #xf3dd
                         :phone-square #xf098
                         :phone-volume #xf2a0
                         :php #xf457
                         :pied-piper #xf2ae
                         :pied-piper-alt #xf1a8
                         :pied-piper-pp #xf1a7
                         :piggy-bank #xf4d3
                         :pills #xf484
                         :pinterest #xf0d2
                         :pinterest-p #xf231
                         :pinterest-square #xf0d3
                         :plane #xf072
                         :play #xf04b
                         :play-circle #xf144
                         :playstation #xf3df
                         :plug #xf1e6
                         :plus #xf067
                         :plus-circle #xf055
                         :plus-square #xf0fe
                         :podcast #xf2ce
                         :poo #xf2fe
                         :pound-sign #xf154
                         :power-off #xf011
                         :prescription-bottle #xf485
                         :prescription-bottle-alt #xf486
                         :print #xf02f
                         :procedures #xf487
                         :product-hunt #xf288
                         :pushed #xf3e1
                         :puzzle-piece #xf12e
                         :python #xf3e2
                         :qq #xf1d6
                         :qrcode #xf029
                         :question #xf128
                         :question-circle #xf059
                         :quidditch #xf458
                         :quinscape #xf459
                         :quora #xf2c4
                         :quote-left #xf10d
                         :quote-right #xf10e
                         :random #xf074
                         :ravelry #xf2d9
                         :react #xf41b
                         :readme #xf4d5
                         :rebel #xf1d0
                         :recycle #xf1b8
                         :red-river #xf3e3
                         :reddit #xf1a1
                         :reddit-alien #xf281
                         :reddit-square #xf1a2
                         :redo #xf01e
                         :redo-alt #xf2f9
                         :registered #xf25d
                         :rendact #xf3e4
                         :renren #xf18b
                         :reply #xf3e5
                         :reply-all #xf122
                         :replyd #xf3e6
                         :resolving #xf3e7
                         :retweet #xf079
                         :ribbon #xf4d6
                         :road #xf018
                         :rocket #xf135
                         :rocketchat #xf3e8
                         :rockrms #xf3e9
                         :rss #xf09e
                         :rss-square #xf143
                         :ruble-sign #xf158
                         :rupee-sign #xf156
                         :safari #xf267
                         :sass #xf41e
                         :save #xf0c7
                         :schlix #xf3ea
                         :scribd #xf28a
                         :search #xf002
                         :search-minus #xf010
                         :search-plus #xf00e
                         :searchengin #xf3eb
                         :seedling #xf4d8
                         :sellcast #xf2da
                         :sellsy #xf213
                         :server #xf233
                         :servicestack #xf3ec
                         :share #xf064
                         :share-alt #xf1e0
                         :share-alt-square #xf1e1
                         :share-square #xf14d
                         :shekel-sign #xf20b
                         :shield-alt #xf3ed
                         :ship #xf21a
                         :shipping-fast #xf48b
                         :shirtsinbulk #xf214
                         :shopping-bag #xf290
                         :shopping-basket #xf291
                         :shopping-cart #xf07a
                         :shower #xf2cc
                         :sign #xf4d9
                         :sign-in-alt #xf2f6
                         :sign-language #xf2a7
                         :sign-out-alt #xf2f5
                         :signal #xf012
                         :simplybuilt #xf215
                         :sistrix #xf3ee
                         :sitemap #xf0e8
                         :skyatlas #xf216
                         :skype #xf17e
                         :slack #xf198
                         :slack-hash #xf3ef
                         :sliders-h #xf1de
                         :slideshare #xf1e7
                         :smile #xf118
                         :smoking #xf48d
                         :snapchat #xf2ab
                         :snapchat-ghost #xf2ac
                         :snapchat-square #xf2ad
                         :snowflake #xf2dc
                         :sort #xf0dc
                         :sort-alpha-down #xf15d
                         :sort-alpha-up #xf15e
                         :sort-amount-down #xf160
                         :sort-amount-up #xf161
                         :sort-down #xf0dd
                         :sort-numeric-down #xf162
                         :sort-numeric-up #xf163
                         :sort-up #xf0de
                         :soundcloud #xf1be
                         :space-shuttle #xf197
                         :speakap #xf3f3
                         :spinner #xf110
                         :spotify #xf1bc
                         :square #xf0c8
                         :square-full #xf45c
                         :stack-exchange #xf18d
                         :stack-overflow #xf16c
                         :star #xf005
                         :star-half #xf089
                         :staylinked #xf3f5
                         :steam #xf1b6
                         :steam-square #xf1b7
                         :steam-symbol #xf3f6
                         :step-backward #xf048
                         :step-forward #xf051
                         :stethoscope #xf0f1
                         :sticker-mule #xf3f7
                         :sticky-note #xf249
                         :stop #xf04d
                         :stop-circle #xf28d
                         :stopwatch #xf2f2
                         :strava #xf428
                         :street-view #xf21d
                         :strikethrough #xf0cc
                         :stripe #xf429
                         :stripe-s #xf42a
                         :studiovinari #xf3f8
                         :stumbleupon #xf1a4
                         :stumbleupon-circle #xf1a3
                         :subscript #xf12c
                         :subway #xf239
                         :suitcase #xf0f2
                         :sun #xf185
                         :superpowers #xf2dd
                         :superscript #xf12b
                         :supple #xf3f9
                         :sync #xf021
                         :sync-alt #xf2f1
                         :syringe #xf48e
                         :table #xf0ce
                         :table-tennis #xf45d
                         :tablet #xf10a
                         :tablet-alt #xf3fa
                         :tablets #xf490
                         :tachometer-alt #xf3fd
                         :tag #xf02b
                         :tags #xf02c
                         :tape #xf4db
                         :tasks #xf0ae
                         :taxi #xf1ba
                         :telegram #xf2c6
                         :telegram-plane #xf3fe
                         :tencent-weibo #xf1d5
                         :terminal #xf120
                         :text-height #xf034
                         :text-width #xf035
                         :th #xf00a
                         :th-large #xf009
                         :th-list #xf00b
                         :themeisle #xf2b2
                         :thermometer #xf491
                         :thermometer-empty #xf2cb
                         :thermometer-full #xf2c7
                         :thermometer-half #xf2c9
                         :thermometer-quarter #xf2ca
                         :thermometer-three-quarters #xf2c8
                         :thumbs-down #xf165
                         :thumbs-up #xf164
                         :thumbtack #xf08d
                         :ticket-alt #xf3ff
                         :times #xf00d
                         :times-circle #xf057
                         :tint #xf043
                         :toggle-off #xf204
                         :toggle-on #xf205
                         :trademark #xf25c
                         :train #xf238
                         :transgender #xf224
                         :transgender-alt #xf225
                         :trash #xf1f8
                         :trash-alt #xf2ed
                         :tree #xf1bb
                         :trello #xf181
                         :tripadvisor #xf262
                         :trophy #xf091
                         :truck #xf0d1
                         :truck-loading #xf4de
                         :truck-moving #xf4df
                         :tty #xf1e4
                         :tumblr #xf173
                         :tumblr-square #xf174
                         :tv #xf26c
                         :twitch #xf1e8
                         :twitter #xf099
                         :twitter-square #xf081
                         :typo3 #xf42b
                         :uber #xf402
                         :uikit #xf403
                         :umbrella #xf0e9
                         :underline #xf0cd
                         :undo #xf0e2
                         :undo-alt #xf2ea
                         :uniregistry #xf404
                         :universal-access #xf29a
                         :university #xf19c
                         :unlink #xf127
                         :unlock #xf09c
                         :unlock-alt #xf13e
                         :untappd #xf405
                         :upload #xf093
                         :usb #xf287
                         :user #xf007
                         :user-circle #xf2bd
                         :user-md #xf0f0
                         :user-plus #xf234
                         :user-secret #xf21b
                         :user-times #xf235
                         :users #xf0c0
                         :ussunnah #xf407
                         :utensil-spoon #xf2e5
                         :utensils #xf2e7
                         :vaadin #xf408
                         :venus #xf221
                         :venus-double #xf226
                         :venus-mars #xf228
                         :viacoin #xf237
                         :viadeo #xf2a9
                         :viadeo-square #xf2aa
                         :vial #xf492
                         :vials #xf493
                         :viber #xf409
                         :video #xf03d
                         :video-slash #xf4e2
                         :vimeo #xf40a
                         :vimeo-square #xf194
                         :vimeo-v #xf27d
                         :vine #xf1ca
                         :vk #xf189
                         :vnv #xf40b
                         :volleyball-ball #xf45f
                         :volume-down #xf027
                         :volume-off #xf026
                         :volume-up #xf028
                         :vuejs #xf41f
                         :warehouse #xf494
                         :weibo #xf18a
                         :weight #xf496
                         :weixin #xf1d7
                         :whatsapp #xf232
                         :whatsapp-square #xf40c
                         :wheelchair #xf193
                         :whmcs #xf40d
                         :wifi #xf1eb
                         :wikipedia-w #xf266
                         :window-close #xf410
                         :window-maximize #xf2d0
                         :window-minimize #xf2d1
                         :window-restore #xf2d2
                         :windows #xf17a
                         :wine-glass #xf4e3
                         :won-sign #xf159
                         :wordpress #xf19a
                         :wordpress-simple #xf411
                         :wpbeginner #xf297
                         :wpexplorer #xf2de
                         :wpforms #xf298
                         :wrench #xf0ad
                         :x-ray #xf497
                         :xbox #xf412
                         :xing #xf168
                         :xing-square #xf169
                         :y-combinator #xf23b
                         :yahoo #xf19e
                         :yandex #xf413
                         :yandex-international #xf414
                         :yelp #xf1e9
                         :yen-sign #xf157
                         :yoast #xf2b1
                         :youtube #xf167
                         :youtube-square #xf431) by #'cddr
          do (setf (gethash k table) (make-string 1 :initial-element (code-char v))))
    table))

(defun name->icon (keyword)
  (gethash keyword *icon-name-map*))
